allow-flight=true
difficulty=hard
enable-command-block=false
gamemode=survival
hardcore=false
level-name=world
motd=HardcorePlus v0.7.1
online-mode=true
pvp=true
spawn-protection=0
view-distance=8
simulation-distance=6
